export const CREDIT_REQUIREMENTS = {
  GENERATE_IMAGE: {
    standard: 5,
    pro: 10,
  },
  REMOVE_BACKGROUND: 5,
  EXTRACT_TEXT: 5,
  UPSCALE: 5,
  COMPRESS_IMAGE: 5,
  CONVERT_FORMAT: 5,
  RESIZE_IMAGE: 5,
  EDIT_IMAGE: 10,
  CROP_ROTATE_FLIP: 5,
  ENHANCE_PROMPT: 2,
};

export const BILLING_CONSTANTS = {
  MIN_CREDITS: 500,
  MIN_AMOUNT: 5,
};

export const SUBSCRIPTION_STANDARD_PLAN_ID =
  process.env.PAYPAL_ENVIRONMENT === 'Sandbox'
    ? process.env.PAYPAL_SANDBOX_STANDARD_PLAN_ID!
    : process.env.PAYPAL_LIVE_STANDARD_PLAN_ID!;

export const SUBSCRIPTION_STANDARD_PLAN_CREDITS = 900;

export const SUBSCRIPTION_PLAN_CREDITS = {
  [SUBSCRIPTION_STANDARD_PLAN_ID]: SUBSCRIPTION_STANDARD_PLAN_CREDITS,
};

export const SUBSCRIPTION_PLAN_NAMES = {
  [SUBSCRIPTION_STANDARD_PLAN_ID]: 'Standard',
};

export const RAZORPAY_SUBSCRIPTION_STANDARD_PLAN_ID =
  process.env.RAZORPAY_ENVIRONMENT === 'test'
    ? process.env.RAZORPAY_TEST_SUBSCRIPTION_STANDARD_PLAN_ID!
    : process.env.RAZORPAY_LIVE_SUBSCRIPTION_STANDARD_PLAN_ID!;

export const RAZORPAY_SUBSCRIPTION_STANDARD_PLAN_CREDITS = 900;

export const RAZORPAY_SUBSCRIPTION_PLAN_CREDITS = {
  [RAZORPAY_SUBSCRIPTION_STANDARD_PLAN_ID]:
    RAZORPAY_SUBSCRIPTION_STANDARD_PLAN_CREDITS,
};

export const RAZORPAY_SUBSCRIPTION_PLAN_NAMES = {
  [RAZORPAY_SUBSCRIPTION_STANDARD_PLAN_ID]: 'Standard',
};

export const USER_SUBSCRIPTION_PLANS = {
  Standard: 'Standard',
};
