export const CREDIT_REQUIREMENTS = {
  GENERATE_IMAGE: {
    standard: 2,
    pro: 6,
  },
  REMOVE_BACKGROUND: 2,
  EXTRACT_TEXT: 2,
  UPSCALE: 2,
  COMPRESS_IMAGE: 2,
  CONVERT_FORMAT: 2,
  RESIZE_IMAGE: 2,
  EDIT_IMAGE: 6,
};
