export const CREDIT_REQUIREMENTS = {
  GENERATE_IMAGE: {
    standard: 5,
    pro: 10,
  },
  REMOVE_BACKGROUND: 5,
  EXTRACT_TEXT: 5,
  UPSCALE: 5,
  COMPRESS_IMAGE: 5,
  CONVERT_FORMAT: 5,
  RESIZE_IMAGE: 5,
  EDIT_IMAGE: 10,
  CROP_ROTATE_FLIP: 5,
  ENHANCE_PROMPT: 2,
};

export const BILLING_CONSTANTS = {
  MIN_CREDITS: 500,
};

export const SUBSCRIPTION_STANDARD_PLAN_ID =
  process.env.PAYPAL_ENVIRONMENT === "Sandbox"
    ? process.env.PAYPAL_SANDBOX_STANDARD_PLAN_ID!
    : process.env.PAYPAL_LIVE_STANDARD_PLAN_ID!;

export const SUBSCRIPTION_STANDARD_PLAN_CREDITS = 900;

export const SUBSCRIPTION_PLAN_CREDITS = {
  [SUBSCRIPTION_STANDARD_PLAN_ID]: SUBSCRIPTION_STANDARD_PLAN_CREDITS,
};

export const SUBSCRIPTION_PLAN_NAMES = {
  [SUBSCRIPTION_STANDARD_PLAN_ID]: "Standard",
};
