export const ROUTES = {
  HOME: "/",
  BLOG: "/blog",
  PRICING: "/pricing",
  CONTACT: "/contact",
  LOGIN: "/login",
  SIGNUP: "/signup",
  FORGOT_PASSWORD: "/forgot-password",
  CHANGE_PASSWORD: "/change-password",
  PRIVACY_POLICY: "/privacy-policy",
  TERMS_OF_SERVICE: "/terms-of-service",
  VERIFY_EMAIL: "/verify-email",

  DASHBOARD: {
    ROOT: "/dashboard",
    GENERATE_IMAGE: "/dashboard/generate-image",
    REMOVE_BACKGROUND: "/dashboard/remove-background",
    EXTRACT_TEXT: "/dashboard/extract-text",
    UPSCALE: "/dashboard/upscale",
    COMPRESS_IMAGE: "/dashboard/compress-image",
    CONVERT_FORMAT: "/dashboard/convert-format",
    RESIZE_IMAGE: "/dashboard/resize-image",
    EDIT_IMAGE: "/dashboard/edit-image",
    CROP_ROTATE_FLIP: "/dashboard/crop-rotate-flip",
    BILLING: "/dashboard/billing",
    SETTINGS: "/dashboard/settings",
  },
};
