name: Deploy to Self-Hosted Runner

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy application
        run: |
          cd ~/imagify
          git pull
          npm install
          npx prisma migrate dev
          npx prisma generate
          npm run build
          pm2 delete imagify || true
          pm2 start npm --name "imagify" -- start